package com.example.KDBS.enums;

public enum BookingStatus {
    PENDING_PAYMENT,
    PENDING_DEPOSIT_PAYMENT,
    PENDING_BALANCE_PAYMENT,
    WAITING_FOR_APPROVED,
    BOOKING_REJECTED,
    WAITING_FOR_UPDATE,
    BOOKING_FAILED,
    BOOKING_BALANCE_SUCCESS,
    BOOKING_SUCCESS_PENDING,
    BOOKING_SUCCESS_WAIT_FOR_CONFIRMED,
    BOOKING_UNDER_COMPLAINT,
    BOOKING_SUCCESS,
    BOOKING_CANCELLED
}